// AUTO-GENERATED by scripts/generate-units.ts
// Do not edit manually. Regenerate with: npm run generate-units
// Source: study-material-database/course_list.json
// Generated: 2026-05-20T23:29:40.715Z

import type { Unit } from "@/lib/types";

export const units: Unit[] = [
  {
    "code": "BSBCMM511",
    "name": "Communicate with influence",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBCRT511",
    "name": "Develop critical thinking in others",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBCRT611",
    "name": "Apply critical thinking for complex problem solving",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBLDR523",
    "name": "Lead and manage effective workplace relationships",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBLDR601",
    "name": "Lead and manage organisational change",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBLDR602",
    "name": "Provide leadership across the organisation",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBOPS502",
    "name": "Manage business operational plans",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBOPS601",
    "name": "Develop and implement business plans",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBPMG532",
    "name": "Manage project quality",
    "trainingPackage": "BSB",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBPMG534",
    "name": "Manage project human resources",
    "trainingPackage": "BSB",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBPMG632",
    "name": "Manage program risk",
    "trainingPackage": "BSB",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBSTR601",
    "name": "Manage innovation and continuous improvement",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBTEC302",
    "name": "Design and produce spreadsheets",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBTWK502",
    "name": "Manage team effectiveness",
    "trainingPackage": "BSB",
    "sectorId": "business",
    "sectorLabel": "Business",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "BSBWHS616",
    "name": "Apply safe design principles to control WHS risks",
    "trainingPackage": "BSB",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE001",
    "name": "Facilitate the empowerment of older people",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE003",
    "name": "Coordinate services for older people",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE004",
    "name": "Implement interventions with older people at risk",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE005",
    "name": "Provide support to people living with dementia",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE011",
    "name": "Provide support to people living with dementia",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCAGE013",
    "name": "Work effectively in aged care",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS003",
    "name": "Increase the safety of individuals at risk of suicide",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS004",
    "name": "Assess co-existing needs",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS006",
    "name": "Facilitate individual service planning and delivery",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS007",
    "name": "Develop and implement service programs",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS011",
    "name": "Meet personal support needs",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS017",
    "name": "Provide loss and grief support",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS019",
    "name": "Recognise and respond to crisis situations",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS023",
    "name": "Support independence and wellbeing",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS025",
    "name": "Support relationships with carers and families",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS031",
    "name": "Provide individualised support",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS033",
    "name": "Identify and report abuse",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS036",
    "name": "Support relationships with carer and family",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS038",
    "name": "Facilitate the empowerment of people receiving support",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS040",
    "name": "Support independence and wellbeing",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS041",
    "name": "Recognise healthy body systems",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCCS044",
    "name": "Follow established person-centred behaviour supports",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCCOM005",
    "name": "Communicate and work in health or community services",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS007",
    "name": "Facilitate the empowerment of people with disability",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS011",
    "name": "Contribute to ongoing skills development using a strengths-based approach",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS012",
    "name": "Support community participation and social inclusion",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS015",
    "name": "Develop and provide person-centred service responses",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS017",
    "name": "Facilitate community participation and social inclusion",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS018",
    "name": "Facilitate ongoing skills development using a person-centred approach",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS019",
    "name": "Provide person-centred services to people with disability with complex needs",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIS020",
    "name": "Work effectively in disability support",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCDIV001",
    "name": "Work with diverse peopleCHC33021",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCLEG001",
    "name": "Work legally and ethically",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCMHS001",
    "name": "Work with people with mental health issues",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCMHS003",
    "name": "Provide recovery oriented mental health services",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CHCMHS011",
    "name": "Assess and promote social, emotional and physical wellbeing",
    "trainingPackage": "CHC",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "CPPBDN6106",
    "name": "Produce building information modelling for building design projects",
    "trainingPackage": "CPP",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "HLTAID011",
    "name": "Provide First Aid",
    "trainingPackage": "HLT",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "HLTHPS006",
    "name": "Assist clients with medication",
    "trainingPackage": "HLT",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "HLTINF006",
    "name": "Apply basic principles and practices of infection prevention and control",
    "trainingPackage": "HLT",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "HLTWHS002",
    "name": "Follow safe work practices for direct client care",
    "trainingPackage": "HLT",
    "sectorId": "community-services",
    "sectorLabel": "Community Services",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "MEM23004A",
    "name": "Apply technical mathematics",
    "trainingPackage": "MEM",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "MEM30031",
    "name": "Operate computer-aided design (CAD) system to produce basic drawing elements",
    "trainingPackage": "MEM",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "RIICluster1",
    "name": "Cluster 1 – Building technical foundations (Stage 1)",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICluster2",
    "name": "Cluster 2 – Building Technical Foundations (Stage 2)",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICluster3",
    "name": "Cluster 3 – Developing technical skills",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICluster4",
    "name": "Cluster 4 - Working with data",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICluster5",
    "name": "Cluster 5 – The Civil Design Professional (Stage 1)",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICluster6",
    "name": "Cluster 6 - Preparing Detailed Designs (Stage 1)",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": true,
    "clusterUnits": []
  },
  {
    "code": "RIICWD512E",
    "name": "Prepare detailed design of motorways and interchanges",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "RIICWD533E",
    "name": "Prepare detailed design of civil concrete structures",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "RIICWD601E",
    "name": "Manage civil works design processes",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "RIILAT402E",
    "name": "Provide leadership in the supervision of diverse work teams",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  },
  {
    "code": "RIIQUA601E",
    "name": "Establish and maintain a quality system",
    "trainingPackage": "RII",
    "sectorId": "engineering-construction",
    "sectorLabel": "Engineering & Construction",
    "deliveryModes": [
      "Classroom",
      "Workplace"
    ],
    "isCluster": false,
    "clusterUnits": []
  }
];

export const unitCount = 69;

export const sectorCounts: Record<string, number> = {
  "business": 11,
  "engineering-construction": 18,
  "community-services": 40
};
